### ISSUE TITLE
Run time error: AttributeError: 'IP' object has no attribute 'off'

### ISSUE THREAD

**Issue by CidoLiu** [NikolaiT/zardaxt#2]
Hello, Sir.

I'm so interesting in your great job, but when I try to run your code, there is a run time error, the full message as follows:

`1617880617: 192.168.2.104:44146 -> 123.125.66.163:80 [SYN]
Traceback (most recent call last):
  File "tcp_fingerprint.py", line 356, in main
    tcpProcess(pkt, layer, ts)
  File "tcp_fingerprint.py", line 194, in tcpProcess
    [df, mf, offset] = computeIPOffset(ip4.off)
AttributeError: 'IP' object has no attribute 'off'
`

**Comment by CidoLiu** [comment]
pypacker had change the "off" to "frag_off"
